// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTF87qKfV9t0zmNtd-KB05KECn8VKxb8w',
    appId: '1:657285918016:web:1aac3eaa0d5b964515dea5',
    messagingSenderId: '657285918016',
    projectId: 'gestor-financiero-28ac2',
    authDomain: 'gestor-financiero-28ac2.firebaseapp.com',
    storageBucket: 'gestor-financiero-28ac2.firebasestorage.app',
    measurementId: 'G-PGGKV0BDFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAFR6oLrlbrMC6p6KgWFCO6yXYHMs7RAU',
    appId: '1:657285918016:android:72ba5daf3469006515dea5',
    messagingSenderId: '657285918016',
    projectId: 'gestor-financiero-28ac2',
    storageBucket: 'gestor-financiero-28ac2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMaZ8YNLnU2HiJEj4o0VwIDFRw1G8b9ik',
    appId: '1:657285918016:ios:bff0ec53a461640415dea5',
    messagingSenderId: '657285918016',
    projectId: 'gestor-financiero-28ac2',
    storageBucket: 'gestor-financiero-28ac2.firebasestorage.app',
    iosBundleId: 'com.example.gestorDeGastosJc',
  );
}
